spring.application.name=pawpal
server.port=8080

# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.egazdcrkxkqdwihbtyoy&password=Danise@123!
spring.datasource.username=postgres
spring.datasource.password=Danise@123!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=ThisIsAVeryLongSecretKeyForPawPalJWTTokenGeneration2026
jwt.expiration=86400000

# Google Authentication
google.client.id=46076906009-33vp9geqsngv3poo133m1ieppnc0qpj6.apps.googleusercontent.com
